# Generated by Django 2.0.7 on 2018-11-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligaciones',
            name='tasa_obligacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
