# Generated by Django 2.0.7 on 2018-11-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20181126_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='acredor',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
